### ISSUE TITLE
hardcoded apiUrl

### ISSUE THREAD

**Issue by j-chimienti** [alexdupre/bitpay-scala#3]
Issue:

BitPayClient has a hardcoded variable `apiUrl` which prevents me from using the library for my instance of btcpayserver

**Comment by alexdupre** [comment]
I've pushed a few changes to support BTCPay server, let me know if anything is missing. Once confirmed I'll release a new version.

**Comment by j-chimienti** [comment]
The new apply method looks good. The requirements  enforce scheme and valid baseUrl '/'. I can't think of anything else I'd want to add at the moment

**Comment by alexdupre** [comment]
Just released version 2.4 with BTCPay support.
